# Generated by Django 5.0.3 on 2024-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(verbose_name="estoque atual"),
        ),
    ]
